"""Build static GitHub Pages site: python3 tools/web/build.py"""
from pathlib import Path
from html import escape as esc
import json, zipfile
from content import units, examples, questions
import questions as question_bank
ROOT=Path(__file__).resolve().parents[2]
WEB=ROOT/'web'

def dump(path,obj): path.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def nav(prefix): return f'''<a class="skip" href="#main">본문으로 건너뛰기</a><header class="top"><a class="brand" href="{prefix}index.html"><span class="brand-mark">Py<span>_</span></span>인공지능 파이썬 실무</a><nav aria-label="주 메뉴"><a href="{prefix}before-you-start.html">시작하기 전에</a><a href="{prefix}units/unit01/index.html">01 모듈</a><a href="{prefix}units/unit02/index.html">02 GUI</a></nav></header>'''
def layout(title,body,prefix='',unit=0): return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} · AI Python Lab</title><meta name="description" content="교과서와 함께 배우는 인공지능 파이썬 실무. 모듈·패키지·tkinter·PySide6 실습과 130개 연습 문제."><link rel="stylesheet" href="{prefix}assets/style.css"></head><body data-unit="{unit}" data-prefix="{prefix}">{nav(prefix)}{body}<footer><p>미림마이스터고등학교 · 2학년 · 함기훈 선생님</p><p>교과서: 멘토르 「인공지능 파이썬 실무」 · 2026학년도 2학기 운영 계획 기반</p><a href="{prefix}sources.html">출처·교과서 대응표·보완 사항</a> · <a href="https://www.mtrschool.co.kr/post/3095" target="_blank" rel="noopener">멘토르 교과서 안내 ↗</a></footer><div id="toast" role="status" aria-live="polite"></div><script src="{prefix}assets/app.js" defer></script></body></html>'''

def progress_tools(): return '''<div class="record-tools"><button data-export>학습 기록 내보내기</button><label class="file-button">기록 불러오기<input type="file" data-import accept="application/json,.json"></label><button data-clear>이 브라우저의 기록 지우기</button></div><p class="small">코드·풀이·저널은 이 브라우저에 저장됩니다. 다른 PC에서는 기록 파일을 불러오세요. 공용 PC에서는 내보낸 뒤 기록을 지우세요. 서버로 제출되거나 공식 성적으로 처리되지 않습니다.</p>'''

home='''<main id="main"><section class="hero home-hero"><div><p class="eyebrow">2026 · SECOND SEMESTER / PYTHON LAB</p><h1>읽고, 바꾸고,<br><em>직접 만들어 보세요.</em></h1><p class="lead">교과서의 한 줄이 나만의 프로그램이 될 때까지.<br>모듈부터 데스크톱 앱까지, 손으로 익히는 파이썬 실습실.</p><div class="actions"><a class="button primary" href="units/unit01/index.html">1단원 시작하기 <span>↗</span></a><a class="button" id="resume" href="before-you-start.html">이어서 학습하기 →</a></div><div class="hero-stats"><span><b>02</b> 학습 단원</span><span><b>130</b> 연습 문제</span><span><b>06</b> GUI 비교 화면</span></div></div><div class="code-art" aria-label="모듈과 GUI를 연결하는 코드 예시"><div class="code-top"><span>● ● ●</span><span>my_first_app.py</span></div><pre><span class="dim"># 배운 기능을 앱으로 연결하기</span>
<span class="gold">from</span> core.logic <span class="gold">import</span> roll

<span class="gold">def</span> on_click():
    result = roll(<span class="mint">6</span>)
    label.setText(str(result))

button.clicked.connect(on_click)</pre><div class="art-output"><span class="status-dot"></span>아이디어 → 코드 → 실행 → 내 것으로</div><div class="art-card"><span>STEP 02</span><b>같은 기능, 두 가지 GUI</b><small>tkinter ↔ PySide6</small></div></div></section><section class="section" aria-labelledby="path-title"><div class="section-head"><div><p class="eyebrow">YOUR LEARNING PATH</p><h2 id="path-title">오늘은 어디부터 시작할까요?</h2></div><span class="pill">개념 → 실습 → 도전</span></div><a class="prep-card" href="before-you-start.html"><span class="number">00</span><div><h3>시작하기 전에</h3><p>Python · VS Code · Git · 디버깅 · AI 도구 설정을 준비하세요.</p></div><span>환경 준비하기 ↗</span></a><div class="course-grid">'''
for u,title,desc,tags in [(1,'모듈과 패키지 활용','코드를 나누고 연결하면서 재사용 가능한 나만의 도구를 만듭니다.',['다중 파일 실행','표준 라이브러리','60문제']),(2,'GUI 프로그래밍','tkinter로 원리를 익히고, 같은 앱을 PySide6로 확장합니다.',['실제 화면 비교','메모장 만들기','70문제'])]:
 home+=f'''<a class="course-card" href="units/unit0{u}/index.html"><div class="course-top"><span class="number">0{u}</span><span class="arrow">↗</span></div><h3>{title}</h3><p>{desc}</p><div class="tags">{''.join(f'<span>{t}</span>' for t in tags)}</div><div class="progress-label"><span>학습 진행</span><span data-unit-progress="{u}">0%</span></div><progress data-unit-bar="{u}" max="100" value="0" aria-label="{u}단원 진행도"></progress></a>'''
home+='''</div><p style="margin:24px 0"><a href="https://www.mtrschool.co.kr/post/3095" target="_blank" rel="noopener">멘토르 「인공지능 파이썬 실무」 교과서 안내 ↗</a> · <a href="sources.html">교과서와 실습 대응표</a></p><div class="future-grid"><div><span>03 · 준비 중</span><h3>파이썬과 머신러닝</h3><p>데이터 준비부터 모델 평가까지</p></div><div><span>04 · 준비 중</span><h3>파이썬과 컴퓨터 비전</h3><p>이미지 처리부터 검출 앱까지</p></div></div></section><section class="section record"><p class="eyebrow">MY WORKSPACE</p><h2>내 학습 기록</h2>'''+progress_tools()+'''</section></main>'''
(WEB/'index.html').write_text(layout('실습실',home))

pairs=[('hello-tk','hello-pyside','첫 인사 앱'),('widgets-tk','widgets-pyside','위젯 도감'),('layout-tk','layout-pyside','레이아웃'),('memo-tk','memo-pyside','메모장'),('project-tk','project-pyside','생활 도우미'),('memo-plus-tk','memo-plus-pyside','개선 메모장')]

def editor_markup(u): return f'''<section class="lab" id="lab"><div class="section-head"><div><p class="eyebrow">CODE WORKSPACE</p><h2>코드를 바꾸는 실습실</h2></div><span class="pill" id="run-mode">실행 환경</span></div><label>예제 선택<select id="example-select" aria-label="예제 선택"></select></label><p id="example-note" class="note"></p><div class="editor-layout"><aside class="file-panel"><p class="eyebrow">PROJECT FILES</p><div id="file-tree"></div><button id="add-file">+ 파일 추가</button><button id="delete-file">현재 파일 삭제</button></aside><div class="editor-main"><div class="editor-bar"><strong id="file-name">main.py</strong><div><button id="copy-code">복사</button><button id="download-file">파일 저장</button></div></div><label class="sr-only" for="code-editor">Python 소스 편집기</label><textarea id="code-editor" spellcheck="false" autocapitalize="off"></textarea></div></div><div class="input-grid"><label>실행 파일<select id="entry-file"></select></label><label>input()에 전달할 값 · 한 줄에 하나<textarea id="stdin" rows="2" placeholder="6"></textarea></label><label>실행 인자 · JSON 문자열 배열<input id="argv" value='[]' placeholder='["param1", "param2"]'></label></div><div class="actions"><button class="primary" id="run">Python 실행</button><button id="check-example">검사</button><button id="stop" disabled>중지</button><button id="reset-code">예제 원본 복원</button><button id="download-project">프로젝트 ZIP</button></div><p class="small" id="runtime-info">실행 엔진은 처음 실행할 때 내려받습니다. 네트워크가 필요합니다. 실행은 최대 15초이며 중지 후 다시 실행할 수 있습니다.</p><pre id="output" role="status" aria-live="polite">실행할 예제를 선택하세요.</pre></section>'''

def practice(u): return f'''<section id="practice" class="section exercise-section"><p class="eyebrow">PRACTICE / RETRY / UNDERSTAND</p><h2>연습 문제 <span class="count">{60 if u==1 else 70}</span></h2><p>실행 검사는 결과와 입력 조건을 확인합니다. 빈칸은 대표 답안과 비교하며, 다른 표현은 해설을 보고 판단하세요. GUI 코드는 PC 실행 점검까지 마치세요.</p><div class="filter-row"><label>유형<select id="question-kind"><option value="">모든 유형</option></select></label><label>상태<select id="question-status"><option value="">전체</option><option value="todo">미완료</option><option value="retry">다시 풀기</option><option value="done">완료</option></select></label><label>검색<input id="question-search" type="search" placeholder="예: 임포트, 메모장"></label></div><p id="question-summary" aria-live="polite"></p><div id="questions"></div><div class="actions"><button id="previous-questions">← 이전 문제</button><span id="question-page"></span><button id="next-questions">다음 문제 →</button></div></section>'''

def simulator(): return '''<section id="simulator" class="section"><p class="eyebrow">INTERACTIVE GUI CONCEPTS</p><h2>눈으로 확인하는 이벤트와 배치</h2><p class="note">학습용 웹 시뮬레이션입니다. 아래 조작은 정해진 예제의 동작을 재현하며, 편집한 Python 코드를 실행하지 않습니다. 실제 tkinter·PySide6 창은 프로젝트를 내려받아 PC에서 실행하세요.</p><div class="sim-grid"><div class="demo-window"><div class="code-top">인사 앱 · 동작 체험</div><div class="demo-body"><label>이름<input id="demo-name" placeholder="이름을 입력하세요"></label><div class="actions"><button id="demo-greet" class="primary">인사하기</button><button id="demo-reset">초기화</button></div><p id="demo-result" aria-live="polite">이름을 입력하세요.</p><pre id="event-log">이벤트를 기다립니다.</pre></div></div><div class="demo-window"><div class="code-top">레이아웃 · 동작 체험</div><div class="demo-body"><label>배치 방식<select id="demo-layout"><option value="vertical">수직 · pack / QVBoxLayout</option><option value="horizontal">수평 · pack(side) / QHBoxLayout</option><option value="grid">격자 · grid / QGridLayout</option></select></label><div id="layout-preview" class="vertical"><button>A</button><button>B</button><button>C</button><button>D</button></div><p class="small">창 너비를 바꿔 배치 변화를 확인하세요.</p></div></div></div><div class="demo-window memo-demo"><div class="code-top">메모장 · 웹 동작 체험</div><div class="demo-body"><div class="actions"><label class="file-button">텍스트 열기<input type="file" id="demo-open" accept="text/plain,.txt"></label><button id="demo-save">텍스트 저장</button><button id="demo-new">새 문서</button></div><label for="demo-memo">메모 내용</label><textarea id="demo-memo" rows="6" placeholder="한글을 입력하고 저장한 뒤 다시 열어 보세요."></textarea><p id="demo-stats" aria-live="polite">0자 · 0줄</p></div></div></section>'''

gallery_items=[('tk','tkinter','Tcl/Tk 8.6','기본 위젯 · 간단한 도구','hello-tk'),('ttk','tkinter + ttk','Tcl/Tk 8.6','테마 위젯 · tkinter 확장','hello-ttk'),('pyside','PySide6','6.11.2 / Qt 6.11.2','Qt 공식 바인딩 · Qt Widgets','hello-pyside'),('pyqt','PyQt6','6.11.0 / Qt 6.11.2','Qt 바인딩 · 풍부한 위젯','hello-pyqt'),('wx','wxPython','4.2.3 / wxWidgets 3.2','OS 위젯 · 데스크톱 도구','hello-wx'),('kivy','Kivy','2.3.1','자체 렌더링 · 터치 UI','hello-kivy')]
def gallery():
 s='<section id="gallery" class="section"><p class="eyebrow">SAME TASK, DIFFERENT TOOLKITS</p><h2>실제 실행 화면으로 비교하세요.</h2><p>모두 이름 입력·인사·초기화 기능을 갖춘 앱입니다. Linux 가상 디스플레이에서 제공 소스를 실행해 캡처했습니다. OS·테마에 따라 외형은 달라집니다. Kivy 예제는 기본 글꼴에서도 보이도록 영어 문구를 사용합니다.</p><div class="gallery-grid">'
 for id,title,version,desc,example in gallery_items:
  s+=f'<article class="gallery-card"><a href="../../assets/screenshots/{id}.png" target="_blank" rel="noopener"><img src="../../assets/screenshots/{id}.png" loading="lazy" alt="{title} 인사 앱 실제 실행 화면 · 이름 입력창과 인사 및 초기화 버튼"></a><div><h3>{title}</h3><p>{desc}</p><small>{version}</small><button data-example="{example}">코드 열기 ↗</button></div></article>'
 s+='</div><h3>같은 기능의 코드 나란히 보기</h3><label>비교할 앱<select id="compare-select">'+''.join(f'<option value="{i}">{title}</option>' for i,(_,_,title) in enumerate(pairs))+'</select></label><div class="actions" role="group" aria-label="코드 보기 방식"><button data-view="both" aria-pressed="true">나란히</button><button data-view="tk" aria-pressed="false">tkinter</button><button data-view="qt" aria-pressed="false">PySide6</button></div><div id="compare" class="compare-grid"><div data-side="tk"><h4>tkinter</h4><pre id="compare-tk"></pre></div><div data-side="qt"><h4>PySide6</h4><pre id="compare-qt"></pre></div></div><p>위젯 도감·레이아웃·메모장·생활 도우미까지 같은 개념을 대응하여 볼 수 있습니다. 실제 수정과 파일 다운로드는 실습실에서 진행하세요.</p></section>'
 return s

for u,lessons in units.items():
 prefix='../../'
 title='모듈과 패키지 활용' if u==1 else 'GUI 프로그래밍'
 ids=list(dict.fromkeys(e for l in lessons for e in l['examples']))
 dump(WEB/f'data/unit{u}.json',dict(unit=u,lessons=lessons,examples={k:examples[k] for k in ids},questions=[q for q in questions if q['unit']==u],pairs=pairs if u==2 else []))
 rail=''.join(f'<a href="#{l["id"]}"><span>{i+1:02}</span>{esc(l["title"])}</a>' for i,l in enumerate(lessons))
 body=f'<section class="unit-hero"><p class="eyebrow">UNIT 0{u} / LEARN BY DOING</p><h1>{title}</h1><p>{"여러 파일을 연결하여 나만의 기능 패키지를 만드세요." if u==1 else "tkinter로 시작하고 PySide6로 확장하는 데스크톱 앱 실습."}</p><div class="tags"><span>교과서 {"8–39" if u==1 else "40–59"}쪽</span><span>필수 과정 6차시</span><span>12파실0{u}-01~03</span><span>{len(lessons)}개 학습 주제</span></div><div class="actions"><a class="button primary" href="#lab">실습실 바로가기</a><a class="button" href="#practice">문제 풀기</a><a class="button" href="../../downloads/unit{u}-examples.zip">전체 예제 ZIP ↓</a></div></section><div class="course-layout"><aside class="rail"><p class="eyebrow">IN THIS UNIT</p>{rail}<a href="#lab">코드 실습실</a>'+('<a href="#gallery">GUI 비교 갤러리</a><a href="#simulator">웹 동작 체험</a>' if u==2 else '')+'<a href="#practice">연습 문제</a><a href="#journal">학습 저널</a></aside><main id="main">'
 for i,l in enumerate(lessons):
  body+=f'<section class="lesson" id="{l["id"]}"><div class="lesson-meta"><span>LESSON {i+1:02}</span><span>{"확장" if l["extra"] else "교과서 연계"} · {l["pages"]}</span></div><h2>{esc(l["title"])}</h2><p class="lesson-lead">{esc(l["lead"])}</p>'+''.join(f'<p>{esc(p)}</p>' for p in l['paragraphs'])
  if l['examples']:
   body+='<div class="example-links">'+''.join(f'<button data-example="{e}"><span>{"▶ 웹 실행" if examples[e]["mode"]=="web" else "↗ PC 실습"}</span>{esc(examples[e]["title"])}</button>' for e in l['examples'])+'</div>'
  if l['tasks']: body+='<div class="task-box"><h3>직접 해 보세요</h3><ol>'+''.join(f'<li>{esc(t)}</li>' for t in l['tasks'])+'</ol></div>'
  body+=f'<label class="completion"><input type="checkbox" data-complete="u{u}-{l["id"]}"> 이 주제를 실습하고 설명할 수 있습니다.</label></section>'
 body+=editor_markup(u)
 if u==2: body+=gallery()+simulator()
 body+=practice(u)+f'''<section id="journal" class="section record"><p class="eyebrow">LEARNING JOURNAL</p><h2>오늘 배운 것을 내 말로</h2><label>오늘 이해한 개념<textarea data-journal="u{u}-learn" rows="3"></textarea></label><label>발생한 오류 · 원인 · 해결 근거<textarea data-journal="u{u}-error" rows="3"></textarea></label><label>시험한 입력과 결과 · 다음에 도전할 것<textarea data-journal="u{u}-next" rows="3"></textarea></label><button id="download-journal">저널 Markdown 저장</button>'''+progress_tools()+'</section><div class="actions end-nav">'+('<a class="button primary" href="../unit02/index.html">다음: GUI 프로그래밍 →</a>' if u==1 else '<a class="button" href="../unit01/index.html">← 모듈과 패키지 복습</a>')+'</div></main></div>'
 (WEB/f'units/unit0{u}/index.html').write_text(layout(title,body,prefix,u))
 with zipfile.ZipFile(WEB/f'downloads/unit{u}-examples.zip','w',zipfile.ZIP_DEFLATED) as z:
  for id in ids:
   e=examples[id]
   for name,source in e['files'].items(): z.writestr(f'{id}/{name}',source)
   packages='PySide6' if 'pyside' in id else 'PyQt6' if 'pyqt' in id else 'wxPython' if '-wx' in id else 'Kivy' if 'kivy' in id else 'numpy' if id=='thirdparty' else ''
   if packages and 'requirements.txt' not in e['files']: z.writestr(f'{id}/requirements.txt',packages+'\n')
   z.writestr(f'{id}/README.md',f'# {e["title"]}\n\n이 폴더를 VS Code로 열고 `python {e["entry"]}`로 실행하세요.\n'+(f'먼저 가상환경에서 `python -m pip install -r requirements.txt`로 {packages}를 설치하세요.\n' if packages else '')+f'\n{e["note"]}\n')
  z.writestr('README.md','각 예제의 폴더를 따로 열어 실행하세요. tkinter는 일부 Linux에서 python3-tk 설치가 필요합니다.\n웹 예제의 input 값은 사이트에 안내되어 있습니다. 실행 인자 sys 예제: python main.py param1 param2\n')

sourcebody='<main id="main" class="source-page"><p class="eyebrow">SOURCES & COVERAGE</p><h1>출처와 학습 범위</h1><p>멘토르 「인공지능 파이썬 실무」 PDF와 2026학년도 2학기 교수·학습 및 평가 운영 계획 _g를 바탕으로 작성했습니다. 교과서 개념·예제·문항의 학습 목표를 웹 실습으로 재구성하고, 확장 내용은 표시했습니다. 원본 교과서 PDF는 사이트에 배포하지 않습니다.</p><h2>교과서 대응표</h2><div class="table-wrap"><table><thead><tr><th>단원</th><th>쪽</th><th>학습 내용</th></tr></thead><tbody>'
for u,ls in units.items():
 for l in ls: sourcebody+=f'<tr><td>{u}</td><td>{l["pages"]}</td><td><a href="units/unit0{u}/index.html#{l["id"]}">{l["title"]}</a></td></tr>'
sourcebody+='</tbody></table></div><h2>정답과 설명 보완</h2><ul><li>정답편 198–203쪽과 대조했습니다. 39쪽 마지막 출력은 코드 실행에 따라 5로 바로잡았습니다(정답편 201쪽은 9).</li><li>25쪽 star 탐구의 함수/모듈 임포트 표현 차이를 설명합니다.</li><li>random.uniform 끝 값, sample의 중복 값 의미, __all__의 적용 범위를 보완합니다.</li><li>날짜 예제는 실행 시점을 기준으로 하고 다음 크리스마스의 연도 전환을 처리합니다.</li><li>58쪽 4번의 사용자 정의 예외 표현을 GUI 사례 분류로 정리했습니다.</li><li>배포판에 따라 tkinter 설치가 필요할 수 있으며, GUI 코드는 PC 실행 대상으로 표시합니다.</li></ul><h2>공식 참고 자료</h2><ul>'
for title,url in [('멘토르 인공지능 파이썬 실무 교과서','https://www.mtrschool.co.kr/post/3095'),('Python 모듈과 패키지','https://docs.python.org/ko/3/tutorial/modules.html'),('Python 표준 라이브러리','https://docs.python.org/ko/3/library/'),('random의 정확한 동작','https://docs.python.org/3/library/random.html'),('tkinter와 ttk','https://docs.python.org/3/library/tkinter.html'),('PySide6 시작하기','https://doc.qt.io/qtforpython-6/gettingstarted.html'),('Qt 시그널과 슬롯','https://doc.qt.io/qtforpython-6/tutorials/basictutorial/signals_and_slots.html'),('PyQt','https://www.riverbankcomputing.com/software/pyqt/'),('wxPython','https://wxpython.org/'),('Kivy','https://kivy.org/doc/stable/'),('PyPI','https://pypi.org/'),('Pyodide 브라우저 제약','https://pyodide.org/en/stable/usage/wasm-constraints.html')]: sourcebody+=f'<li><a href="{url}" target="_blank" rel="noopener">{title} ↗</a></li>'
sourcebody+='</ul><h2>수업·평가 연결</h2><p>1단원과 2단원은 각 6차시의 필수 경로를 두고 확장 학습을 별도로 제공합니다. 수행① 평가 요소는 기능·이벤트 10점, 모듈 구조·코드 품질 5점, 저널 5점입니다. 웹 점수는 연습용이며 공식 성적이나 제출 기록을 대체하지 않습니다.</p><h2>실행 환경</h2><p>브라우저 Python은 Pyodide 0.27.7을 고정하여 사용합니다. 최초 실행에는 CDN 접속이 필요합니다. 다중 파일 실행은 가상 폴더에서 진행합니다. GUI는 코드 문법 확인과 웹 시뮬레이션을 제공하며 실제 동작은 PC에서 확인합니다.</p></main>'
(WEB/'sources.html').write_text(layout('출처와 대응표',sourcebody))
(WEB/'.nojekyll').touch()
print(f'Built {len(examples)} examples / {len(questions)} questions / {sum(map(len,units.values()))} lessons')
